[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
authors = ["Techcable <git@techcable.net>"]
edition = "2021"
# What CSES supports - https://cses.fi/howto/
rust-version = "1.75"
publish = false

[workspace.dependencies]
# What CSES supports - https://cses.fi/howto/
rand = "=0.8.4"

criterion = "0.8"
# Useful for testing
indoc = "2"
itertools = "0.15"
proptest = "1"
# seems to give slightly better output than pretty_assertions,
# but unfortunately disables colors with cargo nextest (see issue mitsuhiko/similar-asserts#10)
# The latter can be fixed using `CLICOLOR_FORCE=1`, which is set automatically by `inv test`.
similar-asserts = "2"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

## aggressively lint casts ##
# in an ideal world, overflowing casts would panic
# linting them (with deny) is the second best option

cast_lossless = "allow" # lossless casts are fine, lints will catch if types change
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_ptr_alignment = "deny"
cast_sign_loss = "deny"
char_lit_as_u8 = "deny"
fn_to_numeric_cast = "deny"
fn_to_numeric_cast_any = "deny"
fn_to_numeric_cast_with_truncation = "deny"
ptr_as_ptr = "allow" # pointer casts are fine as long as they don't violate another rule

#
# clippy::restrictions group
#

get_unwrap = "warn" # Vec.get().unwrap() is silly
infinite_loop = "deny" # I dislike the loop{} pattern
redundant_test_prefix = "warn" # name test_foo is redundant with #[test] attr
same_name_method = "warn" # this is usually a mistake
tests_outside_test_module = "warn"
unnecessary_self_imports = "warn"
unused_result_ok = "warn" # pointless

# specifically bad for CSES problems

unreadable_literal = "allow"

#
# excessively pedantic (even for clippy::pedantic)
#

collapsible_else_if = "allow"
items_after_statements = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
return_self_not_must_use = "allow"
single_match = "allow"

[profile.dev]
# Increases performance with 007-two-knights(n=5000) from ~10s to ~3s
# Using opt-level=2 takes ~600ms and opt-level=3 takes ~300ms
opt-level = 1

[profile.release]
# Reduces performance of 007-two-knights(n=10_000) by 10%, but panic="abort" reduces this to only 6%
overflow-checks = true
lto = true
panic = "abort"

[profile.test]
# Increases performance of slow tests noticeably (sometimes by x2)
# Using opt-level=3 makes a much smaller difference (so likely not worth the added compile time)
opt-level = 2
