[package]
name = "cses-problems-intro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "The introductory CSES problems"
publish.workspace = true

[[bench]]
bench = false
harness = false
name = "binomial_coefficients"

[dependencies]
rand.workspace = true

[dev-dependencies]
criterion.workspace = true
indoc.workspace = true
itertools.workspace = true
similar-asserts.workspace = true

[lints]
workspace = true
